### ISSUE TITLE
link to your paper

### ISSUE THREAD

**Issue by yingweima2022** [AwdHanPeng/TPTrans#1]
Hello,Han

Hi, thanks for your excellent work.

Your paper "Integrating Tree Path in Transformer for Code Representation​"​ is very nice,but I didn't find the link to your paper. Can you provide a way to read your paper?

thank you!

Ma Yingwei

myw@nudt.edu.cn

**Comment by AwdHanPeng** [comment]
Hi, the paper link has been added to the Readme file. 
Please don't hesitate to contact me if you have any questions.
Best wishes.

**Comment by yingweima2022** [comment]
Thanks！
