### ISSUE TITLE
appendix

### ISSUE THREAD

**Issue by tianxiexiaozhu77** [AwdHanPeng/TPTrans#3]
Hello,Han

Hi, thanks for your excellent work.

Your paper "Integrating Tree Path in Transformer for Code Representation​"​ is very nice,but I didn't find the appendix of your paper.  In the code, there is a reference to 'see appendix about the efficient computation of relative path encoding for details.' I would like to understand 'path_map' and 'r_path_idx.' Could you provide a way to read your appendix when it is convenient for you?)

thank you!

Zhang

**Comment by AwdHanPeng** [comment]
Hi, see
https://openreview.net/attachment?id=70Q_NeHImB3&name=supplementary_material

**Comment by tianxiexiaozhu77** [comment]
Thanks！
